# File              : configure.yml
# Author            : Rustam Khafizov <super.rustamm@gmail.com>
# Date              : 06.09.2020
# Last Modified Date: 06.09.2020
# Last Modified By  : Rustam Khafizov <super.rustamm@gmail.com>

---
- name: disabling swap
  become: true
  shell: "swapoff -a && sed -i '/ swap / s/^/#/' /etc/fstab"

- name: ensuring that br_netfilter module is loaded
  become: true
  modprobe:
    name: br_netfilter
    state: present

- name: adding net.bridge config to sysctl
  become: true
  copy:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf
  register: result

- name: applying sysctl config
  become: true
  shell: "sysctl --system"
  when: result.changed

- name: allowing master specific firewall rules
  become: true
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item }}"
    in_interface: "{{ ansible_facts['default_ipv4']['interface'] }}"
    jump: ACCEPT
    state: present
  loop:
    - "6443"
    - "2379:2380"
    - "10250:10252"
